version: '3.3'
networks:
  backend:
    external:
      name: monitor
services:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.4
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend
    ports:
       - 8080:8080
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
