global:
  evaluation_interval: 15s
  scrape_interval: 15s

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets: ['repo.lab.com:8080','server1.lab.com:8080']

#- job_name: 'cadvisor'
#  dns_sd_configs:
#    - names:
#        - 'tasks.cadvisor'
#      type: 'A'
#      port: 8080
